/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package modul5;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Adinda puspitasari
 */
public class frame2 extends javax.swing.JInternalFrame {
    private boolean isEdit = false;
    private int totalHarga;
    
    /**
     * Creates new form frame2
     */
    public frame2() {
        initComponents();
        tampil_data();
      
    }
    
    public void reset() {
        eBarang.setSelectedIndex(0);
        eKode.setText(null);
        eHarga.setText(null);
        eNama.setText(null);
        eJumlah.setText(null);
        eTotal.setText(null);
        ePembayaran.setText(null);
        eKembalian.setText(null);
    }
    
    public void tampil_data(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("namabarang");
        tabel.addColumn("kodebarang");
        tabel.addColumn("hargabarang");
        tabel.addColumn("namapembeli");
        tabel.addColumn("jumlah");
        tabel.addColumn("total");
        tabel.addColumn("bayar");
        tabel.addColumn("kembalian");
        
        try {
            java.sql.Connection conn = modul5.Modul5.koneksiDB();
            String query = "select * from aksesoris";
            java.sql.PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                Object [] row = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6),rs.getString(7),rs.getString(8)};
                tabel.addRow(row);
            }
            
            tabledata.setModel(tabel);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        tbldata = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        eNama = new javax.swing.JTextField();
        eKode = new javax.swing.JTextField();
        eHarga = new javax.swing.JTextField();
        eJumlah = new javax.swing.JTextField();
        eTotal = new javax.swing.JTextField();
        ePembayaran = new javax.swing.JTextField();
        bHitung = new javax.swing.JButton();
        bTotal = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        eBarang = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        eKembalian = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledata = new javax.swing.JTable();
        bHapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nama Pembeli");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel4.setText("Pilih Barang");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel5.setText("Kode Barang");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel6.setText("Harga Barang");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel8.setText("Jumlah Pembelian");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel9.setText("Total Harga");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jLabel10.setText("Total Pembayaran");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));
        jPanel2.add(eNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 110, -1));

        eKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eKodeActionPerformed(evt);
            }
        });
        jPanel2.add(eKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 110, -1));

        eHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eHargaActionPerformed(evt);
            }
        });
        jPanel2.add(eHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 110, -1));

        eJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eJumlahActionPerformed(evt);
            }
        });
        jPanel2.add(eJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 110, -1));
        jPanel2.add(eTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 120, -1));
        jPanel2.add(ePembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 120, -1));

        bHitung.setText("HITUNG");
        bHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungActionPerformed(evt);
            }
        });
        jPanel2.add(bHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        bTotal.setText("TOTAL");
        bTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTotalActionPerformed(evt);
            }
        });
        jPanel2.add(bTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        bReset.setText("RESET");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });
        jPanel2.add(bReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        bSimpan.setText("SIMPAN");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(bSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        eBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Barang", "Anting", "Kalung", "Bandana", "Gelang" }));
        eBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBarangActionPerformed(evt);
            }
        });
        jPanel2.add(eBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 110, -1));

        jLabel7.setText("Kembali");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));
        jPanel2.add(eKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adinda puspitasari\\Documents\\PEMVIS MODUL 5\\bege.jpg")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tbldata.addTab("data", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "namabarang", "kodebarang", "hargabarang", "namapembeli", "jumlah", "total", "bayar", "kembali"
            }
        ));
        tabledata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabledata);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 460, 190));

        bHapus.setText("HAPUS");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        jPanel3.add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adinda puspitasari\\Documents\\PEMVIS MODUL 5\\bege.jpg")); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tbldata.addTab("catatan", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbldata)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbldata)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eKodeActionPerformed

    private void eJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eJumlahActionPerformed

    private void eHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eHargaActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        int selectedRow = tabledata.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih baris yang ingin dihapus.");
        } else {
            int option = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (option == JOptionPane.YES_OPTION) {
                try {
                    String namapembeliToDelete = (String) tabledata.getValueAt(selectedRow, 3);
                    String sql = "DELETE FROM aksesoris WHERE namapembeli = ?";
                    java.sql.Connection conn = (java.sql.Connection) modul5.Modul5.koneksiDB();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setString(1, namapembeliToDelete);
                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus.");
                    tampil_data();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Gagal menghapus data.");
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        int harga = Integer.parseInt(eHarga.getText());
        int jumlah = Integer.parseInt(eJumlah.getText());

        // Hitung total harga
        int totalHarga = harga * jumlah;

        // Tampilkan total harga pada komponen tampilan eTotal
        eTotal.setText(String.valueOf(totalHarga));
    }//GEN-LAST:event_bHitungActionPerformed

    private void bTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTotalActionPerformed
        int bayar = Integer.parseInt(ePembayaran.getText());

        // Ambil total harga dari komponen tampilan
        int totalHarga = Integer.parseInt(eTotal.getText());

        // Hitung kembalian
        int kembalian = bayar - totalHarga;

        if (kembalian < 0) {
            // Kembalian negatif, tampilkan pesan kesalahan
            JOptionPane.showMessageDialog(null, "Maaf, uang yang Anda bayarkan tidak mencukupi. Uang kurang sebesar: Rp " + Math.abs(kembalian));
            eKembalian.setText("Rp 0"); // Atur kembalian menjadi 0
        } else {
            // Tampilkan kembalian pada komponen tampilan eKembalian
            eKembalian.setText("Rp " + kembalian);
        }
    }//GEN-LAST:event_bTotalActionPerformed

    private void eBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBarangActionPerformed
       String pilbar = eBarang.getSelectedItem().toString();
        int harga = 0;
        switch (pilbar) {
            case "Anting" -> {
                eKode.setText("001");
                harga = 15000;
            }
            case "Kalung" -> {
                eKode.setText("002");
                harga = 15000;
            }
            case "Bandana" -> {
                eKode.setText("003");
                harga = 10000;
            }
            case "Gelang" -> {
                eKode.setText("004");
                harga = 8000;
            }
            
            default -> {
                eKode.setText("-");
                eHarga.setText("-");
            }
        }
         eHarga.setText(String.valueOf(harga));
    }//GEN-LAST:event_eBarangActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        try {
        String namabarang = (String) eBarang.getSelectedItem();
        String kodebarang = eKode.getText();
        String hargabarang = eHarga.getText();
        String namapembeli = eNama.getText();
        String jumlah = eJumlah.getText();
        String total = eTotal.getText();
        String bayar = ePembayaran.getText();
        String kembalian = eKembalian.getText();

        if (namabarang.equals("Pilihan") || kodebarang.isEmpty() || hargabarang.isEmpty() || namapembeli.isEmpty() || jumlah.isEmpty() || total.isEmpty() || bayar.isEmpty() || kembalian.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap isi semua kolom data terlebih dahulu.");
        } else {
            if (isEdit) {
                int selectedRow = tabledata.getSelectedRow();
                String namapembeliToUpdate = (String) tabledata.getValueAt(selectedRow, 3); // Ganti dengan kolom yang sesuai
                String sql = "UPDATE aksesoris SET namabarang = ?, kodebarang = ?, hargabarang = ?, namapembeli = ?, jumlah = ?, total = ?, bayar = ?, kembalian = ? WHERE namapembeli = ?";
                java.sql.Connection conn = modul5.Modul5.koneksiDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, namabarang);
                pst.setString(2, kodebarang);
                pst.setString(3, hargabarang);
                pst.setString(4, namapembeli);
                pst.setString(5, jumlah);
                pst.setString(6, total);
                pst.setString(7, bayar);
                pst.setString(8, kembalian);
                pst.setString(9, namapembeliToUpdate);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data berhasil diupdate.");
                isEdit = false;
                bSimpan.setText("Simpan");
            } else {
                // Mode Simpan: Simpan data baru
                String sql = "INSERT INTO aksesoris (namabarang, kodebarang, hargabarang, namapembeli, jumlah, total, bayar, kembalian) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                java.sql.Connection conn = modul5.Modul5.koneksiDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, namabarang);
                pst.setString(2, kodebarang);
                pst.setString(3, hargabarang);
                pst.setString(4, namapembeli);
                pst.setString(5, jumlah);
                pst.setString(6, total);
                pst.setString(7, bayar);
                pst.setString(8, kembalian);
                pst.executeUpdate();
                tbldata.setSelectedIndex(1);
                JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            }
                reset();
                tampil_data();
            }

            tampil_data();
            tbldata.setSelectedIndex(1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        eBarang.setSelectedIndex(0);
        eKode.setText(null);
        eHarga.setText(null);
        eNama.setText(null);
        eJumlah.setText(null);
        eTotal.setText(null);
        ePembayaran.setText(null);
        eKembalian.setText(null);
    }//GEN-LAST:event_bResetActionPerformed

    private void tabledataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledataMouseClicked
        int selectedRow = tabledata.getSelectedRow();

        if (selectedRow != -1) {
            String pilbarValue = (String) tabledata.getValueAt(selectedRow, 0);
            String kodeValue = (String) tabledata.getValueAt(selectedRow, 1);
            String hargaValue = (String) tabledata.getValueAt(selectedRow, 2);
            String namaValue = (String) tabledata.getValueAt(selectedRow, 3);
            String jumlahValue = (String) tabledata.getValueAt(selectedRow, 4);
            String totalValue = (String) tabledata.getValueAt(selectedRow, 5);
            String bayarValue = (String) tabledata.getValueAt(selectedRow, 6);
            String kembalianValue = (String) tabledata.getValueAt(selectedRow, 7);

            eBarang.setSelectedItem(pilbarValue);
            eKode.setText(kodeValue);
            eHarga.setText(hargaValue);
            eNama.setText(namaValue);
            eJumlah.setText(jumlahValue);
            eTotal.setText(totalValue);
            ePembayaran.setText(bayarValue);
            eKembalian.setText(kembalianValue);

            // Mengaktifkan tombol Edit
            bSimpan.setText("Edit");
            isEdit = true; // Menandai bahwa ini adalah mode edit
        }
    }//GEN-LAST:event_tabledataMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bHitung;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTotal;
    private javax.swing.JComboBox<String> eBarang;
    private javax.swing.JTextField eHarga;
    private javax.swing.JTextField eJumlah;
    private javax.swing.JTextField eKembalian;
    private javax.swing.JTextField eKode;
    private javax.swing.JTextField eNama;
    private javax.swing.JTextField ePembayaran;
    private javax.swing.JTextField eTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabledata;
    private javax.swing.JTabbedPane tbldata;
    // End of variables declaration//GEN-END:variables
}
